services:
    nginx:
        image: nginx:1.25.3
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./diary/src:/var/www/
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: ./docker/php
            dockerfile: ./Dockerfile
            args:
                - HOST_UID=${HOST_UID}
                - HOST_GID=${HOST_GID}
        volumes:
            - ./diary/src:/var/www/
        networks:
            - laravel

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80
        networks:
            - laravel

    nuxt:
        build:
            context: ./diary_nuxt
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - laravel

networks:
    laravel:
        driver: bridge